### PR TITLE
Updates astro peer dependency version check for compatibility with bo…

### LINKED ISSUE #33: Peer dependency version issues when using with Astro 1.0.0-beta.x versions
npm ERR! Could not resolve dependency:
npm ERR! peer astro@">=0.23.0" from astro-imagetools@0.4.1
npm ERR! node_modules/astro-imagetools
npm ERR!   astro-imagetools@"^0.4.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: astro@0.26.1
npm ERR! node_modules/astro
npm ERR!   peer astro@">=0.23.0" from astro-imagetools@0.4.1
npm ERR!   node_modules/astro-imagetools
npm ERR!     astro-imagetools@"^0.4.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### PR DESCRIPTION
**Pull request by scottaw66**
Closes #33

### CODE REVIEW

**Comment by RafidMuhymin** [comment]
Thanks for the PR @scottaw66 ! Can you update the PR to change the version range to `>=0.26 || >=1.0.0-beta` ?

**Comment by RafidMuhymin** [comment]
Merging the PR, thanks @scottaw66 for contributing.

**Comment by scottaw66** [comment]
Sorry, didn't see your request in time!

**Comment by scottaw66** [comment]
Weird that I'm still showing the issue... 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: AstroBoy@0.0.1
npm ERR! Found: astro@1.0.0-beta.8
npm ERR! node_modules/astro
npm ERR!   astro@"^1.0.0-beta.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer astro@">=0.23.0" from astro-imagetools@0.4.2
npm ERR! node_modules/astro-imagetools
npm ERR!   astro-imagetools@"^0.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/scott/.npm/eresolve-report.txt for a full report.

**Pull request merged**
