### PR TITLE
Add renderImage function

### PR DESCRIPTION
**Pull request by zadeviggers**
Work in progress.

~~Still to do:~~
- [x] ~~Figure out how to add the `<link rel="preload" />` tag~~
- [x] ~~Figure out how to add the `<style>` tag with background styles~~

### CODE REVIEW

**Comment by RafidMuhymin** [comment]
Thank you @zadeviggers. I'm viewing the code.

**Review by RafidMuhymin — CHANGES_REQUESTED** [review]
:+1: Looks good to me. Can you please remove the `.prettierrc` file?

**Review by RafidMuhymin — APPROVED** [review]
:+1:

**Comment by zadeviggers** [comment]
> 👍 Looks good to me. Can you please remove the `.prettierrc` file?

Okay, I just added it to override my editor's default settings. I'll remove it when I'm finished.

**Comment by zadeviggers** [comment]
Okay, are there any other things I need to change?

**Review by RafidMuhymin — APPROVED** [review]

**Pull request merged**
