### PR TITLE
fix: wrong file name and asset path in astro v2 with vite v4

### PR DESCRIPTION
**Pull request by ixam1**
Hi these 2 changes fixed the plugin working for me with astro v2. It seems like the plugin somehow got faulty file names and asset paths.

I got these changes through trial and error, but I am not sure of the underlying reason why this broke.

Also I am not sure if this breaks the integration with astro v1 or lower.

Maybe someone with more knowledge about how this plugin works can use this PR as a baseline to check why this broke in the first place and if these changes are sufficient.

### CODE REVIEW

**Comment by RafidMuhymin** [comment]
Thanks for reporting the issue @ixam1 but could you please explain the changes you have made. Both of the changes have purposes. And could you please give one or multiple examples of the faulty asset paths and what they should be?

**Comment by ixam1** [comment]
Hi @RafidMuhymin

As I said I dont really know this plugin and its integration with astro/vite enough to understand my changes and their implications myself. I can only tell you that it now work for me flawlessly with astro v2.

I created a reproducable sample astro v2 project with the error on stackblitz, you can check here:

https://stackblitz.com/edit/withastro-astro-1g6kt8?file=src/pages/index.astro

On the index page there is an image loaded with this plugin and when you load the page you will see the error in the console:

`23:58:31 [serve]    404 /assets/[object Object]@500w.30d5d361.jpeg`

Both changes remove some kind of "system default" asset path, maybe these "system default" values changed with vite v4/astro v2.

**Comment by ixam1** [comment]
Seems like you added support for astro v2 in the latest release fixing this, thangs @RafidMuhymin!

**Comment by ixam1** [comment]
Actually it seems to be not fixed, check my stackblitz. I updated it with v0.8 and the error still appears @RafidMuhymin 

https://stackblitz.com/edit/withastro-astro-1g6kt8?file=package.json,src%2Fpages%2Findex.astro

Error:

`23:58:31 [serve]    404 /assets/[object Object]@500w.30d5d361.jpeg`

**Comment by RafidMuhymin** [comment]
Thanks for creating the PR @ixam1, I appreciate your efforts. I have updated the PR. The issue is fixed now.

**Comment by ixam1** [comment]
> Thanks for creating the PR @ixam1, I appreciate your efforts. I have updated the PR. The issue is fixed now.

No problem. Thank you for properly fixing it and maintaining this very useful plugin @RafidMuhymin. 😄

**Pull request merged**
