### PR TITLE
Update config.ts

### PR DESCRIPTION
**Pull request by bronze**
Fix the "Edit this page" links on the docs to point to the correct repo.

### CODE REVIEW

**Comment by RafidMuhymin** [comment]
Thank you @bronze for contributing!

**Comment by IanVS** [comment]
I think the new docs need to be deployed, I'm still seeing this bug, and was about to submit a PR to fix it as well.  :)

**Comment by RafidMuhymin** [comment]
But I am seeing the link has been corrected and is working now. Do you see the change if you hard-reload the page @IanVS?

**Comment by IanVS** [comment]
Looks good now, thanks!

**Pull request merged**
